# ls-lint configuration for loxtep-project-template
# Enforces kebab-case naming for all files and directories

ls:
  demos/**/*:
    .json: kebab-case

  blueprints/**/*:
    .json: kebab-case

  .github:
    .yml: kebab-case

ignore:
  - .git
  - node_modules
